export const jobs = [
    {
        id: 0,
        title: 'Front-end developer',
        company: 'Group',
        description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using making it look like readable English.',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'English',
        contract_type: 'Fulltime'
    },
    {
        id: 1,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'English',
        contract_type: 'Fulltime'
    },
    {
        id: 2,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'English',
        contract_type: 'Fulltime'
    },
    {
        id: 3,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'Dutch',
        contract_type: 'Fulltime'
    },
    {
        id: 4,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'English',
        contract_type: 'Fulltime'
    },
    {
        id: 5,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'Dutch',
        contract_type: 'Fulltime'
    },
    {
        id: 6,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'English',
        contract_type: 'Fulltime'
    },
    {
        id: 7,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'Dutch',
        contract_type: 'Fulltime'
    },
    {
        id: 8,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'English',
        contract_type: 'Fulltime'
    },
    {
        id: 9,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'Dutch',
        contract_type: 'Fulltime'
    },
    {
        id: 10,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'English',
        contract_type: 'Fulltime'
    },
    {
        id: 11,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'Dutch',
        contract_type: 'Fulltime'
    },
    {
        id: 12,
        title: 'Front-end developer',
        company: 'Group',
        description: '',
        short_description: 'Blablabla',
        salary: '100k',
        placed: '22-01-1992',
        postal_code: '3133AT',
        vacancy_language: 'English',
        contract_type: 'Fulltime'
    },
]